### ISSUE TITLE
Static member modelling

### ISSUE THREAD

**Issue by ahueck** [ahueck/llvm-dimeta#21]
Static members and their definitions are currently not well modeled.
The metadata is "separated" and the definition is out of scope of the members parent.

Consider:
```c
struct S {
  static int a[];
};
void bar() {
  S struct_variable;
}
int S::a[10];  // def, complete type
```

Results in metadata:
```llvm
!0 = !DIGlobalVariableExpression(var: !1, expr: !DIExpression())
!1 = distinct !DIGlobalVariable(name: "a", linkageName: "_ZN1S1aE", scope: !2, file: !5, line: 11, type: !6, isLocal: false, isDefinition: true, declaration: !10)
...
!6 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7, size: 320, elements: !8)
!7 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!8 = !{!9}
!9 = !DISubrange(count: 10)
!10 = !DIDerivedType(tag: DW_TAG_variable, name: "a", scope: !11, file: !5, line: 4, baseType: !13, flags: DIFlagStaticMember)
!11 = distinct !DICompositeType(tag: DW_TAG_structure_type, name: "S", file: !5, line: 3, size: 8, flags: DIFlagTypePassByValue, elements: !12, identifier: "_ZTS1S")
!12 = !{!10}
!13 = !DICompositeType(tag: DW_TAG_array_type, baseType: !7, elements: !14)
!14 = !{!15}
!15 = !DISubrange(count: -1)
```

The static member of the struct is only the declaration. The definition is outside of the structure type scopte.
Therefore it is parsed as:
```yaml
Type:
  Compound:
    Name:            S
    Identifier:      _ZTS1S
    Type:            struct
    Extent:          1
    Sizes:           [ 0 ]
    Offsets:         [ 0 ]
    Members:
      - Name:            a
        Builtin:         true
        Type:
          Fundamental:     { Name: int, Extent: 4, Encoding: signed_int }
          Array:           [ 0 ]
          Qualifiers:      [ array, static ]
```

### Notes
Keep this separation?
  * Seems best, and agrees with Clang record decl dump: https://godbolt.org/z/rrdoznTTx
