### ISSUE TITLE
Metadata inheritance parsing to CompoundType  errorneous

### ISSUE THREAD

**Issue by ahueck** [ahueck/llvm-dimeta#29]
Consider https://godbolt.org/z/fx1z5raYr (of test stack_class_inheritance_deep_virtual.cpp) , with layout

```
*** Dumping AST Record Layout
         0 | class Base
         0 |   (Base vtable pointer)
         8 |   double base
           | [sizeof=16, dsize=16, align=8,
           |  nvsize=16, nvalign=8]

*** Dumping AST Record Layout
         0 | class X
         0 |   class Base (primary base)
         0 |     (Base vtable pointer)
         8 |     double base
        16 |   int x
           | [sizeof=24, dsize=20, align=8,
           |  nvsize=20, nvalign=8]

*** Dumping AST Record Layout
         0 | class Y
         0 |   class X (primary base)
         0 |     class Base (primary base)
         0 |       (Base vtable pointer)
         8 |       double base
        16 |     int x
        20 |   float y
           | [sizeof=24, dsize=24, align=8,
           |  nvsize=24, nvalign=8]
```

Parser returns (erroneous sizes/offsets for inherited bases):

```yaml
Type:
  Compound:
    Name:            Y
    Identifier:      _ZTS1Y
    Type:            class
    Extent:          24
    Sizes:           [ 24, 4 ]
    Offsets:         [ 0, 20 ]
    Base:
      - BaseClass:
          Compound:
            Name:            X
            Identifier:      _ZTS1X
            Type:            class
            Extent:          24
            Sizes:           [ 16, 4 ]
            Offsets:         [ 0, 16 ]
            Base:
              - BaseClass:
                  Compound:
                    Name:            Base
                    Identifier:      _ZTS4Base
                    Type:            class
                    Extent:          16
                    Sizes:           [ 8, 8 ]
                    Offsets:         [ 0, 8 ]
                    Members:
                      - Name:            '_vptr$Base'
                        Builtin:         true
                        Type:
                          Fundamental:     { Name: __vtbl_ptr_type, Extent: 8,
                                             Encoding: vtable_ptr }
                          Qualifiers:      [ ptr, ptr ]
                      - Name:            x
                        Builtin:         true
                        Type:
                          Fundamental:     { Name: double, Extent: 8, Encoding: float }
            Members:
              - Name:            y
                Builtin:         true
                Type:
                  Fundamental:     { Name: int, Extent: 4, Encoding: signed_int }
    Members:
      - Name:            z
        Builtin:         true
        Type:
          Fundamental:     { Name: float, Extent: 4, Encoding: float }
```
