### ISSUE TITLE
Enum/EnumClass support

### ISSUE THREAD

**Issue by ahueck** [ahueck/llvm-dimeta#7]
Handle structure of enums with type representation.
For instance, :
```C
enum Color { RED, GREEN, BLUE };
enum Color color = GREEN;
```
with debug data
````C
!20 = !DILocalVariable(name: "color", scope: !17, file: !4, line: 8, type: !3)
!3 = !DICompositeType(tag: DW_TAG_enumeration_type, name: "Color", file: !4, line: 5, baseType: !5, size: 32, elements: !6)
     !5 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)

````
is encoded to
```yaml
Type:
  Compound:
    Name:            Color
    Type:            enum
    Extent:          4
```

This is due to our parser (DIParser.cpp/DimetaParser.cpp) invoking the "composite" event and then the "fundamental" event due to the debug data structure.
